package com.playerblocklife;

import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerQuitEvent;

/**
 * PlayerQuitListener - PlayerBlockLife游戏模式下的玩家退出监听器
 * 
 * <p>处理玩家退出服务器时的日志记录。在PlayerBlockLife游戏模式中，玩家退出不会影响
 * 其生命方块状态，因为方块位置信息仅在服务器运行期间维护。</p>
 * 
 * @author xiaobai
 * @version 2.2.0-1.20.4
 * @since 1.0.0
 */
public class PlayerQuitListener implements Listener {
    private final PlayerBlockLife plugin;

    public PlayerQuitListener(PlayerBlockLife plugin) {
        this.plugin = plugin;
    }

    @EventHandler
    public void onPlayerQuit(PlayerQuitEvent event) {
        plugin.logInfo("玩家 " + event.getPlayer().getName() + " 离开了游戏");
    }
}